const mongoose=require('mongoose');
const Schema=mongoose.Schema;

const setSchema=new Schema({
    bmi:{
        start:{
            type:Number
        },
        end:{
            type:Number
        }
    },
    bod:{
        start:{
            type:Number
        },
        end:{
            type:Number
        }
    },
    workoutTime:{
        start:{
            type:Number
        },
        end:{
            type:Number
        }
    },
    addiction:{
        type:Boolean
    },
    cholesterol:{
        start:{
            type:Number
        },
        end:{
            type:Number
        }
    },
    bloodPressure:{
        start:{
            type:Number
        },
        end:{
            type:Number
        }
    },
    activity:[
        {
            type:mongoose.Schema.Types.ObjectId,
            ref:'activity'
        }
    ],
    admin:{
        type:mongoose.Schema.Types.ObjectId,
        ref:'user'
    },
    leaderboard:[
        {
            userid:{
                type:String
            },
            point:{
                type:Number
            },
            username:{
                type:String
            }
        }
    ]
})

module.exports=mongoose.model('set',setSchema);